---
# Keepalived configuration tasks

- name: Install keepalived
  apt:
    name: keepalived
    state: present
    update_cache: yes

- name: Configure keepalived
  template:
    src: keepalived.conf.j2
    dest: /etc/keepalived/keepalived.conf
    owner: root
    group: root
    mode: '0644'
  register: keepalived_config

- name: Create check_apiserver.sh script
  copy:
    src: check_apiserver.sh
    dest: /etc/keepalived/check_apiserver.sh
    owner: root
    group: root
    mode: '0755'
  register: keepalived_script

- name: Restart keepalived
  systemd:
    name: keepalived
    state: restarted
    enabled: yes
  when: keepalived_config.changed or keepalived_script.changed
