---
# Kubernetes Cluster Cleanup Playbook
# This playbook replicates the functionality of cleanup-k8s.sh
# Run with: ansible-playbook -i inventory.yml playbooks/cleanup-cluster.yml

- name: Cleanup Kubernetes Cluster
  hosts: all
  become: true
  tasks:
    - name: Stop Kubernetes services
      systemd:
        name: "{{ item }}"
        state: stopped
        enabled: no
      with_items:
        - kubelet
        - containerd
        - keepalived
        - haproxy
      ignore_errors: true

    - name: Reset kubeadm
      command: kubeadm reset -f
      ignore_errors: true

    - name: Clean up etcd data
      file:
        path: /var/lib/etcd
        state: absent

    - name: Clean up certificates
      file:
        path: "{{ item }}"
        state: absent
      with_items:
        - /etc/kubernetes/pki/etcd
        - /etc/kubernetes/pki

    - name: Remove configuration files
      file:
        path: "{{ item }}"
        state: absent
      with_items:
        - /etc/kubernetes/admin.conf
        - /etc/kubernetes/kubelet.conf
        - /etc/kubernetes/bootstrap-kubelet.conf
        - /etc/kubernetes/controller-manager.conf
        - /etc/kubernetes/scheduler.conf
        - /etc/kubernetes/kubeadm/kubeadm-init.yaml

    - name: Clean up CNI
      file:
        path: /etc/cni/net.d
        state: absent

    - name: Remove network interfaces
      command: "ip link delete {{ item }} || true"
      with_items:
        - flannel.1
        - cni0
      ignore_errors: true
      changed_when: false

    - name: Clean up containerd directories
      file:
        path: "{{ item }}"
        state: absent
      with_items:
        - /var/lib/containerd/io.containerd.runtime.v1.linux
        - /var/lib/containerd/io.containerd.runtime.v2.task
        - /var/lib/containerd/containerd.sock
        - /etc/crictl.yaml

    - name: Restart containerd
      systemd:
        name: containerd
        state: restarted
        enabled: yes
